blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Dokumentation DataLinq
    url: https://docs.webgiscloud.com/de/datalinq/index.html
    about: Bitte prÃ¼fen Sie zuerst die Dokumentation, ob Ihre Frage dort bereits beantwortet wird.

  - name: ğŸ“š Dokumentation WebGIS-(DataLinq)
    url: https://docs.webgiscloud.com/de/webgis/config/api/index.html#datalinq
    about: Bitte prÃ¼fen Sie zuerst die Dokumentation, ob Ihre Frage dort bereits beantwortet wird.

  - name: ğŸ’¬ Frage stellen / Hilfe & How-to
    url: https://github.com/e-netze/datalinq-community/discussions
    about: Fragen zu Code-Beispielen, SQL-Queries oder allgemeine Hilfe? Bitte hier stellen.
